service:
  name: "boice-blog-api"
  httpPort: 2222
  grpcPort: 2223
  metricPort: 3333
  debug: false
  traceCollectorURL: ""
  env: "dev"
  discoveryServerURL: ""
  password: "chb112233"
database:
  host: "mysql-1710ad7d-datachaihaobo-4323.b.aivencloud.com"
  maxIdle: 10
  maxOpen: 20
  maxIdletime: "1m"
  maxLifetime: "3m"
  name: "defaultdb"
  password: ""
  port: "28953"
  user: "avnadmin"
  location: "Local"
redis:
  address: "localhost:6379"
  password: ""
  index: 0
jwt:
  accessTokenSecretKey: "pW01vkr0Mmm9q15Iep/Aeg=="
  refreshTokenSecretKey: "oW01vkr0Mmm9q15Iep/Aeg=="
  accessTokenDuration: "1h"
  refreshTokenDuration: "360h"
